// Core remedy seed data — the most commonly used homeopathic remedies
// Full materia medica import will come from parsed public domain sources
export const remedies = [
  { abbreviation: "Acon", name: "Aconitum Napellus", commonName: "Monkshood", kingdom: "PLANT", description: "Sudden, intense onset. Fear, shock, anxiety. First stage of acute illness." },
  { abbreviation: "Ars", name: "Arsenicum Album", commonName: "White Arsenic", kingdom: "MINERAL", description: "Restlessness with exhaustion. Burning pains relieved by heat. Anxiety, perfectionism." },
  { abbreviation: "Bell", name: "Belladonna", commonName: "Deadly Nightshade", kingdom: "PLANT", description: "High fever with hot, red, dry skin. Throbbing pains. Sudden onset. Delirium." },
  { abbreviation: "Bry", name: "Bryonia Alba", commonName: "White Bryony", kingdom: "PLANT", description: "Worse from any motion. Dry mucous membranes, thirst for large quantities. Irritable." },
  { abbreviation: "Calc", name: "Calcarea Carbonica", commonName: "Calcium Carbonate", kingdom: "MINERAL", description: "Sluggish, chilly, sweaty. Slow development. Anxious about health and security." },
  { abbreviation: "Cham", name: "Chamomilla", commonName: "German Chamomile", kingdom: "PLANT", description: "Extreme irritability and sensitivity to pain. Teething children. Capricious." },
  { abbreviation: "Dros", name: "Drosera Rotundifolia", commonName: "Sundew", kingdom: "PLANT", description: "Violent spasmodic cough. Whooping cough. Cough worse lying down, after midnight." },
  { abbreviation: "Eup-per", name: "Eupatorium Perfoliatum", commonName: "Boneset", kingdom: "PLANT", description: "Deep bone pain with flu. 'Breakbone fever.' Restlessness, chill, thirst." },
  { abbreviation: "Ferr-p", name: "Ferrum Phosphoricum", commonName: "Iron Phosphate", kingdom: "MINERAL", description: "Early stages of inflammation without marked symptoms. Anemia. Slow onset fever." },
  { abbreviation: "Gels", name: "Gelsemium Sempervirens", commonName: "Yellow Jasmine", kingdom: "PLANT", description: "Flu with heaviness, droopiness, no thirst. Anticipatory anxiety. Weakness." },
  { abbreviation: "Hep", name: "Hepar Sulphuris Calcareum", commonName: "Calcium Sulphide", kingdom: "MINERAL", description: "Oversensitive to pain and cold. Tendency to suppuration. Croup. Splinter-like pains." },
  { abbreviation: "Hyos", name: "Hyoscyamus Niger", commonName: "Henbane", kingdom: "PLANT", description: "Jealousy, suspicion, inappropriate behavior. Twitching. Cough worse lying down." },
  { abbreviation: "Ign", name: "Ignatia Amara", commonName: "St. Ignatius Bean", kingdom: "PLANT", description: "Grief, disappointment, suppressed emotions. Sighing. Contradictory symptoms." },
  { abbreviation: "Kali-bi", name: "Kali Bichromicum", commonName: "Potassium Bichromate", kingdom: "MINERAL", description: "Thick, stringy, yellow-green mucus. Sinus congestion. Pains that shift rapidly." },
  { abbreviation: "Lyc", name: "Lycopodium Clavatum", commonName: "Club Moss", kingdom: "PLANT", description: "Bloating, flatulence, worse 4-8pm. Anticipatory anxiety. Right-sided complaints." },
  { abbreviation: "Merc", name: "Mercurius Solubilis", commonName: "Mercury", kingdom: "MINERAL", description: "Profuse, offensive discharges. Sweating without relief. Trembling. Sensitive to heat and cold." },
  { abbreviation: "Nat-m", name: "Natrum Muriaticum", commonName: "Table Salt", kingdom: "MINERAL", description: "Reserved, dwells on grief. Cold sores, headaches. Aversion to sympathy. Worse at seaside." },
  { abbreviation: "Nux-v", name: "Nux Vomica", commonName: "Poison Nut", kingdom: "PLANT", description: "Oversensitive, irritable, overworked. Digestive complaints. Worse cold, stimulants." },
  { abbreviation: "Phos", name: "Phosphorus", commonName: "Phosphorus", kingdom: "MINERAL", description: "Bright, sympathetic, fearful. Cravings for cold drinks. Bleeding tendencies. Burning pains." },
  { abbreviation: "Puls", name: "Pulsatilla Nigricans", commonName: "Windflower", kingdom: "PLANT", description: "Weepy, clingy, craves comfort. Symptoms shift. Mild disposition. Worse warmth, better open air." },
  { abbreviation: "Rhus-t", name: "Rhus Toxicodendron", commonName: "Poison Ivy", kingdom: "PLANT", description: "Stiffness worse on initial motion, better continued motion. Restlessness. Hot, itchy eruptions." },
  { abbreviation: "Sep", name: "Sepia Officinalis", commonName: "Cuttlefish Ink", kingdom: "ANIMAL", description: "Indifference to loved ones. Hormonal issues. Exhaustion. Better vigorous exercise." },
  { abbreviation: "Sil", name: "Silicea", commonName: "Silica", kingdom: "MINERAL", description: "Lack of confidence, yielding. Poor assimilation. Sweaty head, cold feet. Promotes expulsion." },
  { abbreviation: "Spong", name: "Spongia Tosta", commonName: "Roasted Sponge", kingdom: "ANIMAL", description: "Croup with dry, barking cough. Worse before midnight. Better eating and drinking." },
  { abbreviation: "Sulph", name: "Sulphur", commonName: "Sulphur", kingdom: "MINERAL", description: "Burning, itching eruptions. Untidy, philosophical, selfish. Worse heat, washing." },
];
