// Seed data for repertory/materia medica sources
export const sources = [
  {
    slug: "kent",
    name: "Kent's Repertory",
    author: "James Tyler Kent",
    year: 1897,
    description: "The foundational classical repertory. Comprehensive symptom-to-remedy mapping with grades 1-3.",
    isPublicDomain: true,
  },
  {
    slug: "boericke",
    name: "Boericke's Materia Medica",
    author: "William Boericke",
    year: 1901,
    description: "Widely used materia medica with keynotes, clinical indications, and modalities for each remedy.",
    isPublicDomain: true,
  },
  {
    slug: "boericke-new",
    name: "Boericke's New Manual of Homeopathic Materia Medica",
    author: "William Boericke",
    year: 1927,
    description: "Expanded edition of Boericke's classic, including a full repertory section. The most complete version of his materia medica.",
    isPublicDomain: true,
  },
  {
    slug: "clarke",
    name: "Clarke's Dictionary of Materia Medica",
    author: "John Henry Clarke",
    year: 1900,
    description: "Comprehensive dictionary of materia medica covering over 1,200 remedies.",
    isPublicDomain: true,
  },
  {
    slug: "murphy",
    name: "Murphy's Repertory",
    author: "Robin Murphy",
    year: 1993,
    description: "Modern repertory organized alphabetically. Widely used by contemporary practitioners.",
    isPublicDomain: false,
  },
  {
    slug: "ullman-children",
    name: "Homeopathic Medicine for Children and Infants",
    author: "Dana Ullman",
    year: 1992,
    description: "Practical guide to homeopathic treatment for children and infants. Covers common childhood illnesses with remedy guidance.",
    isPublicDomain: false,
  },
  {
    slug: "castro-handbook",
    name: "The Complete Homeopathy Handbook",
    author: "Miranda Castro",
    year: 1990,
    description: "Accessible and thorough guide to self-prescribing. Covers acute conditions with detailed remedy pictures and materia medica.",
    isPublicDomain: false,
  },
  {
    slug: "apelian-apothecary",
    name: "Forgotten Home Apothecary",
    author: "Nicole Apelian",
    year: 2021,
    description: "Focuses on natural and herbal remedies alongside homeopathic treatments. Practical home reference for families.",
    isPublicDomain: false,
  },
  {
    slug: "meadowcroft-herbalist",
    name: "The Ancient Herbalist and Healer: Natural Remedies",
    author: "Tamsin Meadowcroft",
    year: 2020,
    description: "Combines traditional herbal knowledge with natural remedy guidance. Useful for understanding plant-based and homeopathic overlap.",
    isPublicDomain: false,
  },
  {
    slug: "hershoff-remedies",
    name: "Homeopathic Remedies",
    author: "Asa Hershoff",
    year: 2000,
    description: "A-to-Z guide covering hundreds of conditions with remedy recommendations. Practical reference for home use.",
    isPublicDomain: false,
  },
];
